make configure --whatever --help work as expected
Originally committed as revision 5434 to svn://svn.ffmpeg.org/ffmpeg/trunk

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3,100 +3,101 @@
 # ffmpeg configure script (c) 2000, 2001, 2002 Fabrice Bellard
 #
 
+show_help(){
+  echo "Usage: configure [options]"
+  echo "Options: [defaults in brackets after descriptions]"
+  echo
+  echo "Standard options:"
+  echo "  --help                   print this message"
+  echo "  --prefix=PREFIX          install in PREFIX [$prefix]"
+  echo "  --libdir=DIR             install libs in DIR [PREFIX/lib]"
+  echo "  --incdir=DIR             install includes in DIR [PREFIX/include/ffmpeg]"
+  echo "  --mandir=DIR             install man page in DIR [PREFIX/man]"
+  echo "  --enable-mp3lame         enable MP3 encoding via libmp3lame [default=no]"
+  echo "  --enable-libogg          enable Ogg support via libogg [default=no]"
+  echo "  --enable-vorbis          enable Vorbis support via libvorbis [default=no]"
+  echo "  --enable-theora          enable Theora support via libtheora [default=no]"
+  echo "  --enable-faad            enable FAAD support via libfaad [default=no]"
+  echo "  --enable-faadbin         build FAAD support with runtime linking [default=no]"
+  echo "  --enable-faac            enable FAAC support via libfaac [default=no]"
+  echo "  --enable-libgsm          enable GSM support via libgsm [default=no]"
+  echo "  --enable-xvid            enable XviD support via xvidcore [default=no]"
+  echo "  --enable-x264            enable H.264 encoding via x264 [default=no]"
+  echo "  --enable-mingw32         enable MinGW native/cross Windows compile"
+  echo "  --enable-mingwce         enable MinGW native/cross WinCE compile"
+  echo "  --enable-a52             enable GPLed A52 support [default=no]"
+  echo "  --enable-a52bin          open liba52.so.0 at runtime [default=no]"
+  echo "  --enable-dts             enable GPLed DTS support [default=no]"
+  echo "  --enable-pp              enable GPLed postprocessing support [default=no]"
+  echo "  --enable-static          build static libraries [default=yes]"
+  echo "  --disable-static         do not build static libraries [default=no]"
+  echo "  --enable-shared          build shared libraries [default=no]"
+  echo "  --disable-shared         do not build shared libraries [default=yes]"
+  echo "  --enable-amr_nb          enable amr_nb float audio codec"
+  echo "  --enable-amr_nb-fixed    use fixed point for amr-nb codec"
+  echo "  --enable-amr_wb          enable amr_wb float audio codec"
+  echo "  --enable-amr_if2         enable amr_wb IF2 audio codec"
+  echo "  --enable-sunmlib         use Sun medialib [default=no]"
+  echo "  --enable-pthreads        use pthreads [default=no]"
+  echo "  --enable-dc1394          enable IIDC-1394 grabbing using libdc1394"
+  echo "                           and libraw1394 [default=no]"
+  echo "  --enable-gpl             allow use of GPL code, the resulting libav*"
+  echo "                           and ffmpeg will be under GPL [default=no]"
+  echo ""
+  echo "Advanced options (experts only):"
+  echo "  --source-path=PATH       path to source code [$source_path]"
+  echo "  --cross-prefix=PREFIX    use PREFIX for compilation tools [$cross_prefix]"
+  echo "  --cc=CC                  use C compiler CC [$cc]"
+  echo "  --make=MAKE              use specified make [$make]"
+  echo "  --extra-cflags=ECFLAGS   add ECFLAGS to CFLAGS [$CFLAGS]"
+  echo "  --extra-ldflags=ELDFLAGS add ELDFLAGS to LDFLAGS [$LDFLAGS]"
+  echo "  --extra-libs=ELIBS       add ELIBS [$ELIBS]"
+  echo "  --build-suffix=SUFFIX    suffix for application specific build []"
+  echo "  --cpu=CPU                force cpu to CPU  [$cpu]"
+  echo "  --tune=CPU               tune code for a particular CPU"
+  echo "                           (may fail or perform badly on other CPUs)"
+  echo "  --powerpc-perf-enable    enable performance report on PPC"
+  echo "                           (requires enabling PMC)"
+  echo "  --disable-mmx            disable MMX usage"
+  echo "  --disable-iwmmxt         disable iwmmxt usage"
+  echo "  --disable-altivec        disable AltiVec usage"
+  echo "  --disable-audio-oss      disable OSS audio support [default=no]"
+  echo "  --disable-audio-beos     disable BeOS audio support [default=no]"
+  echo "  --disable-v4l            disable video4linux grabbing [default=no]"
+  echo "  --disable-v4l2           disable video4linux2 grabbing [default=no]"
+  echo "  --disable-bktr           disable bktr video grabbing [default=no]"
+  echo "  --disable-dv1394         disable DV1394 grabbing [default=no]"
+  echo "  --disable-network        disable network support [default=no]"
+  echo "  --disable-zlib           disable zlib [default=no]"
+  echo "  --disable-lzo            disable lzo [default=no]"
+  echo "  --disable-simple_idct    disable simple IDCT routines [default=no]"
+  echo "  --disable-vhook          disable video hooking support"
+  echo "  --enable-gprof           enable profiling with gprof [$gprof]"
+  echo "  --disable-debug          disable debugging symbols"
+  echo "  --disable-opts           disable compiler optimizations"
+  echo "  --disable-mpegaudio-hp   faster (but less accurate)"
+  echo "                           MPEG audio decoding [default=no]"
+  echo "  --disable-protocols      disable I/O protocols support [default=no]"
+  echo "  --disable-ffserver       disable ffserver build"
+  echo "  --disable-ffplay         disable ffplay build"
+  echo "  --enable-small           optimize for size instead of speed"
+  echo "  --enable-memalign-hack   emulate memalign, interferes with memory debuggers"
+  echo "  --disable-strip          disable stripping of executables and shared libraries"
+  echo "  --disable-encoder=NAME   disables encoder NAME"
+  echo "  --enable-encoder=NAME    enables encoder NAME"
+  echo "  --disable-decoder=NAME   disables decoder NAME"
+  echo "  --enable-decoder=NAME    enables decoder NAME"
+  echo "  --disable-encoders       disables all encoders"
+  echo "  --disable-decoders       disables all decoders"
+  echo "  --disable-muxers         disables all muxers"
+  echo "  --disable-demuxers       disables all demuxers"
+  echo ""
+  echo "NOTE: Object files are built at the place where configure is launched."
+  exit 1
+}
+
 if test x"$1" = x"-h" -o x"$1" = x"--help" ; then
-cat << EOF
-
-Usage: configure [options]
-Options: [defaults in brackets after descriptions]
-
-EOF
-echo "Standard options:"
-echo "  --help                   print this message"
-echo "  --prefix=PREFIX          install in PREFIX [$prefix]"
-echo "  --libdir=DIR             install libs in DIR [PREFIX/lib]"
-echo "  --incdir=DIR             install includes in DIR [PREFIX/include/ffmpeg]"
-echo "  --mandir=DIR             install man page in DIR [PREFIX/man]"
-echo "  --enable-mp3lame         enable MP3 encoding via libmp3lame [default=no]"
-echo "  --enable-libogg          enable Ogg support via libogg [default=no]"
-echo "  --enable-vorbis          enable Vorbis support via libvorbis [default=no]"
-echo "  --enable-theora          enable Theora support via libtheora [default=no]"
-echo "  --enable-faad            enable FAAD support via libfaad [default=no]"
-echo "  --enable-faadbin         build FAAD support with runtime linking [default=no]"
-echo "  --enable-faac            enable FAAC support via libfaac [default=no]"
-echo "  --enable-libgsm          enable GSM support via libgsm [default=no]"
-echo "  --enable-xvid            enable XviD support via xvidcore [default=no]"
-echo "  --enable-x264            enable H.264 encoding via x264 [default=no]"
-echo "  --enable-mingw32         enable MinGW native/cross Windows compile"
-echo "  --enable-mingwce         enable MinGW native/cross WinCE compile"
-echo "  --enable-a52             enable GPLed A52 support [default=no]"
-echo "  --enable-a52bin          open liba52.so.0 at runtime [default=no]"
-echo "  --enable-dts             enable GPLed DTS support [default=no]"
-echo "  --enable-pp              enable GPLed postprocessing support [default=no]"
-echo "  --enable-static          build static libraries [default=yes]"
-echo "  --disable-static         do not build static libraries [default=no]"
-echo "  --enable-shared          build shared libraries [default=no]"
-echo "  --disable-shared         do not build shared libraries [default=yes]"
-echo "  --enable-amr_nb          enable amr_nb float audio codec"
-echo "  --enable-amr_nb-fixed    use fixed point for amr-nb codec"
-echo "  --enable-amr_wb          enable amr_wb float audio codec"
-echo "  --enable-amr_if2         enable amr_wb IF2 audio codec"
-echo "  --enable-sunmlib         use Sun medialib [default=no]"
-echo "  --enable-pthreads        use pthreads [default=no]"
-echo "  --enable-dc1394          enable IIDC-1394 grabbing using libdc1394"
-echo "                           and libraw1394 [default=no]"
-echo "  --enable-gpl             allow use of GPL code, the resulting libav*"
-echo "                           and ffmpeg will be under GPL [default=no]"
-echo ""
-echo "Advanced options (experts only):"
-echo "  --source-path=PATH       path to source code [$source_path]"
-echo "  --cross-prefix=PREFIX    use PREFIX for compilation tools [$cross_prefix]"
-echo "  --cc=CC                  use C compiler CC [$cc]"
-echo "  --make=MAKE              use specified make [$make]"
-echo "  --extra-cflags=ECFLAGS   add ECFLAGS to CFLAGS [$CFLAGS]"
-echo "  --extra-ldflags=ELDFLAGS add ELDFLAGS to LDFLAGS [$LDFLAGS]"
-echo "  --extra-libs=ELIBS       add ELIBS [$ELIBS]"
-echo "  --build-suffix=SUFFIX    suffix for application specific build []"
-echo "  --cpu=CPU                force cpu to CPU  [$cpu]"
-echo "  --tune=CPU               tune code for a particular CPU"
-echo "                           (may fail or perform badly on other CPUs)"
-echo "  --powerpc-perf-enable    enable performance report on PPC"
-echo "                           (requires enabling PMC)"
-echo "  --disable-mmx            disable MMX usage"
-echo "  --disable-iwmmxt         disable iwmmxt usage"
-echo "  --disable-altivec        disable AltiVec usage"
-echo "  --disable-audio-oss      disable OSS audio support [default=no]"
-echo "  --disable-audio-beos     disable BeOS audio support [default=no]"
-echo "  --disable-v4l            disable video4linux grabbing [default=no]"
-echo "  --disable-v4l2           disable video4linux2 grabbing [default=no]"
-echo "  --disable-bktr           disable bktr video grabbing [default=no]"
-echo "  --disable-dv1394         disable DV1394 grabbing [default=no]"
-echo "  --disable-network        disable network support [default=no]"
-echo "  --disable-zlib           disable zlib [default=no]"
-echo "  --disable-lzo            disable lzo [default=no]"
-echo "  --disable-simple_idct    disable simple IDCT routines [default=no]"
-echo "  --disable-vhook          disable video hooking support"
-echo "  --enable-gprof           enable profiling with gprof [$gprof]"
-echo "  --disable-debug          disable debugging symbols"
-echo "  --disable-opts           disable compiler optimizations"
-echo "  --disable-mpegaudio-hp   faster (but less accurate)"
-echo "                           MPEG audio decoding [default=no]"
-echo "  --disable-protocols      disable I/O protocols support [default=no]"
-echo "  --disable-ffserver       disable ffserver build"
-echo "  --disable-ffplay         disable ffplay build"
-echo "  --enable-small           optimize for size instead of speed"
-echo "  --enable-memalign-hack   emulate memalign, interferes with memory debuggers"
-echo "  --disable-strip          disable stripping of executables and shared libraries"
-echo "  --disable-encoder=NAME   disables encoder NAME"
-echo "  --enable-encoder=NAME    enables encoder NAME"
-echo "  --disable-decoder=NAME   disables decoder NAME"
-echo "  --enable-decoder=NAME    enables decoder NAME"
-echo "  --disable-encoders       disables all encoders"
-echo "  --disable-decoders       disables all decoders"
-echo "  --disable-muxers         disables all muxers"
-echo "  --disable-demuxers       disables all demuxers"
-echo ""
-echo "NOTE: Object files are built at the place where configure is launched."
-exit 1
+    show_help
 fi
 
 # set temporary file name
@@ -621,6 +622,8 @@ for opt do
   --disable-muxers) muxers="no"; ffserver="no"
   ;;
   --disable-demuxers) demuxers="no"
+  ;;
+  --help) show_help
   ;;
   *)
   echo "Unknown option \"$opt\"."
